export enum ImagesActions {
  GET_LIST_REQUEST = 'GET_LIST_REQUEST',
  GET_LIST_SUCCESS = 'GET_LIST_SUCCESS',
  GET_LIST_FAIL = 'GET_LIST_FAIL',
  UPDATE_RECORD_REQUEST = 'UPDATE_RECORD_REQUEST',
  UPDATE_RECORD_SUCCESS = 'UPDATE_RECORD_SUCCESS',
  UPDATE_RECORD_FAIL = 'UPDATE_RECORD_FAIL',
  CREATE_RECORD_REQUEST = 'CREATE_RECORD_REQUEST',
  CREATE_RECORD_SUCCESS = 'CREATE_RECORD_SUCCESS',
  CREATE_RECORD_FAIL = 'CREATE_RECORD_FAIL',
  REMOVE_RECORD_REQUEST = 'REMOVE_RECORD_REQUEST',
  REMOVE_RECORD_SUCCESS = 'REMOVE_RECORD_SUCCESS',
  REMOVE_RECORD_FAIL = 'REMOVE_RECORD_FAIL',
}
